# Generated by Django 4.0.2 on 2022-02-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_feature_details_feature_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
