# Generated by Django 4.0.2 on 2022-03-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_delete_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='', max_length=30)),
                ('u_name', models.CharField(default='', max_length=30)),
                ('e_mail', models.EmailField(default='', max_length=30)),
                ('phone', models.PositiveIntegerField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=30)),
                ('c_pass', models.CharField(default='', max_length=30)),
                ('dob', models.DateField(default='', max_length=30)),
                ('u_type', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='T_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='', max_length=30)),
                ('u_name', models.CharField(default='', max_length=30)),
                ('e_mail', models.EmailField(default='', max_length=30)),
                ('phone', models.PositiveIntegerField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=30)),
                ('c_pass', models.CharField(default='', max_length=30)),
                ('dob', models.DateField(default='', max_length=30)),
                ('u_type', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
