# Generated by Django 4.0.2 on 2022-03-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_s_data_phone_alter_t_data_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s_data',
            name='c_pass',
        ),
        migrations.RemoveField(
            model_name='s_data',
            name='password',
        ),
        migrations.RemoveField(
            model_name='t_data',
            name='c_pass',
        ),
        migrations.RemoveField(
            model_name='t_data',
            name='password',
        ),
        migrations.RemoveField(
            model_name='t_data',
            name='u_name',
        ),
        migrations.AddField(
            model_name='t_data',
            name='expertise',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='t_data',
            name='languages',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='t_data',
            name='qualification',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='t_data',
            name='rate',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='s_data',
            name='dob',
            field=models.DateField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='s_data',
            name='e_mail',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='s_data',
            name='f_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='s_data',
            name='u_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='s_data',
            name='u_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='t_data',
            name='dob',
            field=models.DateField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='t_data',
            name='e_mail',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='t_data',
            name='f_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='t_data',
            name='u_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
