# Generated by Django 4.0.2 on 2022-03-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_s_data_c_pass_remove_s_data_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_data',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='t_data',
            name='dob',
            field=models.DateField(),
        ),
    ]
