# Generated by Django 4.0.2 on 2022-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_s_data_dob_alter_t_data_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_data',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_data',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
