# Generated by Django 4.0.2 on 2022-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_s_data_dob_alter_t_data_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_data',
            name='overview',
            field=models.TextField(default=''),
        ),
    ]
