# Generated by Django 4.0.2 on 2022-04-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_t_data_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_data',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='t_data',
            name='mode',
            field=models.CharField(default='', max_length=30),
        ),
    ]
