# Generated by Django 4.0.2 on 2022-04-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_t_data_country_t_data_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_data',
            old_name='country',
            new_name='locality',
        ),
    ]
