# Generated by Django 4.0.2 on 2022-04-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_country_t_data_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_data',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
