# Generated by Django 4.0.2 on 2022-05-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_s_data_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(default='', max_length=50)),
                ('tutor', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
